# This is a basic workflow to help you get started with Actions

name: CI
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
    - name: generate sas token for infrastructure storage account
      id: sas_token
      shell: pwsh
      run: |
          end=`date -u -d "5 minutes" '+%Y-%m-%dT%H:%MZ'`
          token=$(az storage container generate-sas \
            --subscription d7a7d108-a259-43c6-8a4c-bfc867f9eb69 \
            --name 'test-container' \
            --account-name 'blobsastokengpk' \
            --as-user \
            --auth-mode login \
            --expiry $end \
            --output tsv \
            --permissions r)
          echo "token=$token" >> $GITHUB_ENV
          echo "SAS token: $token"
    - name: Construct Blob URL with SAS Token
      run: |
          blob_url="https://blobsastokengpk.blob.core.windows.net/test-container/test.txt?${{ env.token }}"
          echo "blob_url=$blob_url" >> $GITHUB_ENV
          echo "Blob URL with SAS token: $blob_url"
    - name: Use Blob URL
      run: |
          echo "Blob URL is ${{ env.blob_url }}"
