# This is a basic workflow to help you get started with Actions

name: CI
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
    - name: generate sas token for infrastructure storage account
      id: sas_token
      shell: pwsh
      run: |
          $end = (Get-Date).AddMinutes(5).ToUniversalTime().ToString("yyyy-MM-ddTHH:mmZ")
          $token = az storage container generate-sas `
            --subscription d7a7d108-a259-43c6-8a4c-bfc867f9eb69 `
            --name 'test-container' `
            --account-name 'blobsastokengpk' `
            --as-user `
            --auth-mode login `
            --expiry $end `
            --output tsv `
            --permissions r `
            --debug
          echo "token=$token" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Host "SAS token: $token"

    - name: Construct Blob URL with SAS Token
      shell: pwsh
      run: |
          $blob_url = "https://blobsastokengpk.blob.core.windows.net/test-container/test.txt?$($env:token)"
          echo "blob_url=$blob_url" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Host "Blob URL with SAS token: $blob_url"

    - name: Use Blob URL
      shell: pwsh
      run: |
          Write-Host "Blob URL is $env:blob_url"
