name: List Azure Role Assignments

on:
  push:
    branches:
      - main

jobs:
  list-role-assignments:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: List role assignments for the logged-in service principal
      shell: pwsh
      run: |
        # Get the Service Principal ID of the logged-in user
        $spId = az ad signed-in-user show --query id -o tsv

        # List role assignments and filter for the logged-in Service Principal ID
        $roleAssignments = az role assignment list --all | ConvertFrom-Json
        $filteredAssignments = $roleAssignments | Where-Object { $_.principalId -eq $spId }

        # Display the filtered role assignments
        $filteredAssignments | Select-Object -Property principalName, roleDefinitionName, scope, createdBy, createdOn | Format-Table -AutoSize
