name: List Azure Role Assignments

on:
  push:
    branches:
      - main

jobs:
  list-role-assignments:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: List role assignments for the logged-in user
      shell: pwsh
      run: |
        # Retrieve Service Principal Object ID
        $spObjectId = az ad sp show --id $(az account show --query user.name -o tsv) --query objectId --output tsv
        Write-Host "Service Principal Object ID: $spObjectId"
        
        # List role assignments for the Service Principal
        $roleAssignments = az role assignment list --assignee $spObjectId --output table
        Write-Host "Role assignments for the Service Principal:"
        Write-Host $roleAssignments
