name: List Azure Role Assignments

on:
  push:
    branches:
      - main

jobs:
  list-role-assignments:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PowerShell
      uses: actions/setup-powershell@v3
      with:
        pwsh-version: '7.x'

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: List role assignments for the logged-in user
      shell: pwsh
      run: |
        # Retrieve Object ID of the currently logged-in user
        $objectId = az ad signed-in-user show --query objectId --output tsv
        Write-Host "Logged-in user Object ID: $objectId"

        # List role assignments for the user
        $roleAssignments = az role assignment list --assignee $objectId --output table
        Write-Host "Role assignments for the logged-in user:"
        Write-Host $roleAssignments
