name: Pass Values b/w steps
on:
  workflow_dispatch

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get current date and time
      id: get_datetime
      shell: pwsh
      run: echo "datetime=$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" >> $env:GITHUB_ENV

    - name: Use the shared value
      shell: pwsh
      run: echo "The current date and time is $env:datetime "
 
