name: set steps output
on:
  workflow_dispatch
  

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get current date and time
      id: get_datetime
      shell: pwsh
      run: |
        $datetime = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
        # echo "datetime=$datetime" >> $env:GITHUB_ENV
        echo "datetime=$datetime" >> $env:GITHUB_OUTPUT
        # echo "::set-output name=datetime::$datetime"

    - name: Use the shared value
      shell: pwsh
      run: echo "The current date and time is $env:datetime"
      env:
        datetime: ${{ steps.get_datetime.outputs.datetime }}
